### ISSUE TITLE
Is this plugin going to die?

### ISSUE THREAD

**Issue by hawken93** [jellyfin-archive/emby-plugin-gamebrowser#1]
I hear we are pulling out of core whatever support there was for game browser, so I think it may be natural to just remove this plugin. In that case I would like the jellyfin team to archive the repository instead of outright deleting it :)

**Comment by cvium** [comment]
Game support has already been removed, so let's archive this.

**Comment by JustAMan** [comment]
I'll go ahead and archive it, if anyone would want to revisit the decision ping me on matrix or via main repo.
